apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vortexflow-ingress
  namespace: vortexflow
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: vortexflow.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: vortexflow-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vortexflow-frontend
                port:
                  number: 80
